# Generated by Django 6.0.2 on 2026-05-15 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multishop_adminapp', '0001_initial'),
        ('multishop_userapp', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('pro_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multishop_adminapp.product')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
