# Generated by Django 6.0.2 on 2026-05-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multishop_userapp', '0003_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_to_card',
            name='pro_quatity',
        ),
        migrations.RemoveField(
            model_name='add_to_card',
            name='total_price',
        ),
    ]
