# Generated by Django 6.0.2 on 2026-05-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multishop_userapp', '0004_remove_add_to_card_pro_quatity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_name', models.CharField(max_length=250)),
                ('house_no', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.IntegerField(max_length=6)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
    ]
