# Generated by Django 6.0.2 on 2026-06-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multishop_userapp', '0009_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='house_no',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='road_name',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='pincode',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='l_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='pin_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
