# Generated by Django 6.0.2 on 2026-05-13 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name1', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('create_at', models.DateField(auto_now_add=True)),
                ('is_action', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='category_sbu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name2', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('create_at', models.DateField(auto_now_add=True)),
                ('is_action', models.BooleanField(default=True)),
                ('category_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multishop_adminapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='category_sub_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name3', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('create_at', models.DateField(auto_now_add=True)),
                ('is_action', models.BooleanField(default=True)),
                ('cate_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multishop_adminapp.category')),
                ('cate_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multishop_adminapp.category_sbu')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('product_image', models.FileField(upload_to='product/')),
                ('product_price', models.IntegerField()),
                ('descount_price', models.IntegerField()),
                ('product_despcrition', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('create_at', models.DateField(auto_now_add=True)),
                ('cate_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multishop_adminapp.category')),
                ('cate_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multishop_adminapp.category_sub_sub')),
                ('cate_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multishop_adminapp.category_sbu')),
            ],
        ),
    ]
