# Generated by Django 6.0.2 on 2026-06-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multishop_adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_sbu',
            name='cat_image',
            field=models.FileField(default=1, upload_to='category_sbu/'),
            preserve_default=False,
        ),
    ]
